import pytest
from src.modules.deepl import DeepL

@pytest.mark.asyncio()
async def test_en_to_ru_one_suggestion() -> None:
    text = """The topic I chose for my third writing assignment is altruism."""
    to_text = """Тема, которую я выбрал для своего третьего письменного задания, - альтруизм."""
    t = DeepL('en', 'ru', timeout=100000)
    res = await t.translate(text)
    res = res.replace("\n", "")
    assert res.replace("\n\n", "") == to_text

@pytest.mark.asyncio()
async def test_en_to_ru_five_suggestion() -> None:
    text = """Advertisements want to persuade us to buy particular products How do they do it? Let's imagine ...You're watching TV. It's a hot evening: You feel thirsty. You see an advert for a refreshing drink. You see people looking cool and relaxed. You notice the name of the refreshing drink because you think it could be useful for you to satisfy your thirst. Advertisers study how people learn so that they can 'teach' them to respond to their advertising."""
    to_text = """Реклама хочет убедить нас купить определенные товары Как она это делает? Давайте представим... Вы смотрите телевизор. Жаркий вечер: Вы чувствуете жажду. Вы видите рекламу освежающего напитка. Вы видите людей, которые выглядят спокойными и расслабленными. Вы обращаете внимание на название освежающего напитка, потому что думаете, что он может быть полезен вам для утоления жажды. Рекламодатели изучают, как люди учатся, чтобы "научить" их реагировать на их рекламу."""
    t = DeepL('en', 'ru', timeout=100000)
    res = await t.translate(text)
    res = res.replace("\n", "")
    assert res.replace("\n\n", "") == to_text

@pytest.mark.asyncio()
async def test_en_to_ru_3000_characters() -> None:
    text = "To Sherlock Holmes she is always the woman. I have seldom heard him mention her under any other name. In his eyes she eclipses and predominates the whole of her sex. It was not that he felt any emotion akin to love for Irene Adler. All emotions, and that one particularly, were abhorrent to his cold, precise but admirably balanced mind. He was, I take it, the most perfect reasoning and observing machine that the world has seen, but as a lover he would have placed himself in a false position. He never spoke of the softer passions, save with a gibe and a sneer. They were admirable things for the observer--excellent for drawing the veil from men's motives and actions. But for the trained reasoner to admit such intrusions into his own delicate and finely adjusted temperament was to introduce a distracting factor which might throw a doubt upon all his mental results. Grit in a sensitive instrument, or a crack in one of his own high-power lenses, would not be more disturbing than a strong emotion in a nature such as his. And yet there was but one woman to him, and that woman was the late Irene Adler, of dubious and questionable memory. I had seen little of Holmes lately. My marriage had drifted us away from each other. My own complete happiness, and the home-centred interests which rise up around the man who first finds himself master of his own establishment, were sufficient to absorb all my attention, while Holmes, who loathed every form of society with his whole Bohemian soul, remained in our lodgings in Baker Street, buried among his old books, and alternating from week to week between cocaine and ambition, the drowsiness of the drug, and the fierce energy of his own keen nature. He was still, as ever, deeply attracted by the study of crime, and occupied his immense faculties and extraordinary powers of observation in following out those clues, and clearing up those mysteries which had been abandoned as hopeless by the official police. From time to time I heard some vague account of his doings:"
    to_text = "Для Шерлока Холмса она всегда женщина. Я редко слышал, чтобы он упоминал ее под каким-либо другим именем. В его глазах она затмевает и преобладает над всеми представителями своего пола. Не то чтобы он испытывал к Ирэн Адлер какие-то эмоции, сродни любви. Все эмоции, а эта особенно, были отвратительны его холодному, точному, но великолепно уравновешенному уму. Он был, как я понимаю, самой совершенной машиной для рассуждений и наблюдений, какую только видел мир, но в качестве любовника он поставил бы себя в ложное положение. Он никогда не говорил о более мягких страстях, только с издевкой и усмешкой. Они были восхитительны для наблюдателя - превосходны для того, чтобы приоткрыть завесу над мотивами и поступками людей. Но для опытного рассуждателя допускать такие вторжения в свой собственный тонкий и точно отрегулированный темперамент означало вводить отвлекающий фактор, который мог поставить под сомнение все его умственные результаты. Зерно в чувствительном инструменте или трещина в одной из его собственных сверхмощных линз были бы не более тревожными, чем сильная эмоция в такой натуре, как его. И все же для него существовала только одна женщина, и этой женщиной была покойная Ирен Адлер, сомнительной и сомнительной памяти. В последнее время я мало видела Холмса. Мой брак отдалил нас друг от друга. Мое собственное счастье и домашние интересы, которые возникают вокруг человека, впервые оказавшегося хозяином в своем доме, поглощали все мое внимание, а Холмс, всей своей богемной душой ненавидевший любую форму общества, оставался в нашем домике на Бейкер-стрит, зарывшись в свои старые книги, и из недели в неделю чередовал кокаин и честолюбие, сонливость наркотика и яростную энергию своей собственной острой натуры. Его по-прежнему, как и прежде, глубоко привлекало изучение преступлений, и он с огромными способностями и необычайной наблюдательностью занимался тем, что искал разгадки и прояснял тайны, которые официальная полиция считала безнадежными. Время от времени я слышал какие-то смутные рассказы о его делах:"
    t = DeepL('en', 'ru', timeout=100000)
    res = await t.translate(text)
    res = res.replace("\n", "")
    assert res.replace("\n\n", "") == to_text
